"""Initial schema from models

Revision ID: 363988352f18
Revises: 
Create Date: 2025-12-02 11:44:46.777441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363988352f18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('funding', sa.BigInteger(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_domain'), ['domain'], unique=False)

    op.create_table('industries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_competitor',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'competitor_id')
    )
    op.create_table('company_industry',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'industry_id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('company_industry')
    op.drop_table('company_competitor')
    op.drop_table('industries')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_domain'))

    op.drop_table('company')
    # ### end Alembic commands ###
