"""Add MarketPositioning model

Revision ID: 45cc21d58f5e
Revises: 61fab210d9c4
Create Date: 2025-12-02 17:18:45.768052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cc21d58f5e'
down_revision = '61fab210d9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_positioning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('competitive_edge', sa.Text(), nullable=True),
    sa.Column('brand_perception', sa.Text(), nullable=True),
    sa.Column('key_segments', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('opportunity_areas', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('linkedin_employees')
        batch_op.drop_column('latest_article')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_article', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linkedin_employees', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('market_positioning')
    # ### end Alembic commands ###
