"""Add competitive_landscape field to company

Revision ID: 61fab210d9c4
Revises: 363988352f18
Create Date: 2025-12-02 13:18:20.128374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fab210d9c4'
down_revision = '363988352f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competitive_landscape', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('competitive_landscape')

    # ### end Alembic commands ###
