"""Add industry and country to company

Revision ID: 7e443e3897bc
Revises: 20251112_supabase_schema
Create Date: 2025-11-12 20:47:05.723513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e443e3897bc'
down_revision = '20251112_supabase_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('account_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('country')
        batch_op.drop_column('industry')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('account_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
