"""Add financial data, website, updated_at to Company

Revision ID: 88caf396b78e
Revises: 20250101_restore_industries
Create Date: 2025-11-30 20:57:10.922576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88caf396b78e'
down_revision = '20250101_restore_industries'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('stock_symbol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stock_exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('funding_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('number_of_employees',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('company_id_key'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_company_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('company_id_key'), ['id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('number_of_employees',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('revenue')
        batch_op.drop_column('funding_stage')
        batch_op.drop_column('stock_exchange')
        batch_op.drop_column('stock_symbol')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
